### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by Patchethium** [SHAREVOX/sharevox_training#4]
Any plan on languages besides Japanese? I could contribute some English and Chinese recipes, the most difference would just be the shape of some tensors and some different g2p modules.

**Comment by y-chan** [comment]
> Any plan on languages besides Japanese? 

No, we don't have plans to create besides Japanese TTS system.
We don't have the knowledge to create besides Japanese TTS system.

Sorry...

**Comment by Patchethium** [comment]
Hmmm... I see, seems creating my own is the only choice, thanks!
